### ISSUE TITLE
Even after opening the 'Let's fly' book in the container app, the download icon is not changing in the app icon.

### ISSUE THREAD

**Issue by Ashish1998** [curiouslearning/CRWebPlayer#11]
**Describe the bug**
When we open the container app and click on Let's fly book it loads the content and the book opens, but if we come back to the container app there we can observe the download icon still displays on the app icon.

**To Reproduce**
1. Download the container app from the latest apk.
2. Open the container app and click on 'Let's Fly' book icon.
3. Click on back button and return to the container app.
4. We can observe the download symbol is still displayed.

**Expected behavior**
Once the user opens the book the download icon should not be displayed.

**Screen Record**

https://images.zenhubusercontent.com/570054738/7a34163f-5219-4029-b8dc-b43e3f4a7915/screenrecorder_2023_03_24_16_28_29_898.mp4

**Smartphone (please complete the following information):**
 - Device: MI Note 6 pro
 - OS: Android 9

**Additional context**

**Comment by burrage** [comment]
Moving to #425:

https://github.com/curiouslearning/FeedTheMonsterJS/issues/425
